# project init
project: "PracticalLearning"
exp_name: "baseline"
save_wandb: True
seed: 3407
num_workers: 8
gpu_ids: "[0]"
val_check: 1.0
# dataset
image_path: "/home/sonwe1e/WorkStation/Dataset/CelebA/"
# train setting
batch_size: 64
learning_rate: 0.00008
weight_decay: 0.002
epochs: 200
image_size: 64
# model setting
channels: [32, 64, 128, 256, 512]
channels_div: 1
latent_dim: 128